name: Deploy Application

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop

jobs:

  create-deployment-artifacts:

    name: Create deployment artifacts

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Compile React

        run: |

          npm config set legacy-peer-deps true

          npm install

          npm run build


      


      - name: Install Composer dependencies

      - uses: shivammathur/setup-php@master

        with:

          php-version: '8.1.9'

      run: composer install --no-dev --no-interaction --prefer-dist



      