name: Deploy Application

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop

jobs:

  create-deployment-artifacts:

    name: Create deployment artifacts

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Compile React

        run: |

          npm config set legacy-peer-deps true

          npm install

          npm run build


      - name: Configure PHP

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1.9'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Update Composer
        run: composer update
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Link public storage
        run: php artisan storage:link
      - name: Create Database & Run Migration
        run: |
          touch database/database.sqlite
          php artisan migrate:fresh


      - name: Create deployment artifact

      env:

        GITHUB_SHA: ${{ hithub.sha }}
      
      run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules *


      - name: Store artifact

        uses: actions/upload-artifact@v2

        with:

          name:  app-build

          path: ${{ github_sha }}.tar.gz

      