name: Deploy Application

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop

jobs:

  create-deployment-artifacts:

    name: Create deployment artifacts

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Compile React

        run: |

          npm config set legacy-peer-deps true

          npm install

          npm run build


      - name: Create deployment artifact

      env:

        GITHUB_SHA: ${{ hithub.sha }}
      
      run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules *


      - name: Store artifact

        uses: actions/upload-artifact@v2

        with:

          name:  app-build

          path: ${{ github_sha }}.tar.gz

      